config/routes.rb
Rails.application.routes.draw do
  resources :films do
    resources :comments
  end
end

app/models/comment.rb
class Comment <ActiveRecord::Base
  belongs_to :film
  validates :name, :post, :presence => true
end

app/models/film.rb
class Film < ActiveRecord::Base
  has_many :comments
  validates :title, :url, :description, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @film = Film.find(params[:film_id])
    @comment = @film.comments.new
  end

  def create
    @film = Film.find(params[:film_id])
    @comment = @film.comments.new(comment_params)
    if @comment.save
      redirect_to film_path(@comment.film)
    else
      render :new
    end
  end

private
  def comment_params
    params.require(:comment).permit(:name, :post)
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  def index
    @films = Film.all
    render :index
  end

  def show
    @film = Film.find(params[:id])
  end

  def new
    @film = Film.new
  end

  def create
    @film = Film.new(film_params)
    if @film.save
      redirect_to films_path
    else
      render :new
    end
  end

  def edit
    @film = Film.find(params[:id])
  end

  def update
    @film = Film.find(params[:id])

    if params[:vote] == 'up'
      @film.votes += 1
      @film.save
      redirect_to films_path
    else
      if @film.update(film_params)
        redirect_to films_path
      else
        render :edit
      end
    end
  end

  def destroy
    @film = Film.find(params[:id])
    @film.destroy
    redirect_to films_path
  end

  private
  def film_params
    params.require(:film).permit(:title, :url, :description, :director, :votes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= render('layouts/errors', :object => @comment) %>

<%= form_for [@film, @comment] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :post %>
  <%= f.text_field :post %>
  <p><%= f.submit %></p>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment for <%= @film.title %></h1>

<%= render 'form' %>

app/views/films/_form.html.erb
<%= render "layouts/errors", :object => @film %>

<%= form_for @film do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title%>
  <%= f.label :director %>
  <%= f.text_field :director%>
  <%= f.label :url %>
  <%= f.text_field :url%>
  <%= f.label :description %>
  <%= f.text_field :description%>
  <%= f.submit %>
<% end %>

app/views/films/edit.html.erb
<h1>Edit Film</h1>

<%= render 'form' %>

app/views/films/index.html.erb
<h1>Films</h1>

<div class="center">
  <div class="row">
      <ul>
        <% @films.each do |film| %>
         <div class="col-md-4 col-md-4 col-md-4">
           <div class="thumbnail" >
           <li><%= link_to image_tag("#{film.url}"), film_path(film) %><br> <%= link_to '^', film_path(film, :vote => "up"), :method => "patch" %> [ <%= film.votes %> stars ] <%= link_to film.title, film_path(film) %> </li>
         </div>
     </div>
           <% end %>
      </ul>

 </div>
</div>
<hr>

<%= link_to "New Film", new_film_path %>

app/views/films/new.html.erb
<h1>New Film</h1>

<%= render "form" %>

app/views/films/show.html.erb
<h1><%= @film.title %></h1>
<h4>directed by <%= @film.director %></h4>
<h5> Star Votes: <%= @film.votes %> </h5>

<% if @film.comments.any? %>
  <h4>Film Reviews:</h4>

  <ul>
    <% @film.comments.each do |comment| %>
    <li>
      <%= comment.name %> thinks: <%= comment.post %>
      <%= link_to "Edit", edit_film_comment_path(@film, comment) %>
      <%= link_to "Delete", film_comment_path(@film, comment),
                            :date => {:confirm => "Sure, sure?",
                                      :method => "delete"} %>
    </li>
   <% end %>
  </ul>
  <% else %>
    <p>No comments to report.</p>
<% end %>



<p><%= link_to "Edit", edit_film_path(@film) %>
   <%= link_to "Delete", film_path(@film),
                         :data => {:confirm => "Sure?",
                                   :method => "delete"} %>

   <%= link_to "Add a Comment", new_film_comment_path(@film) %></p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_message.each do |message|%>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Films What</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<header>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class"navbar-header">
        <a class="navbar-brand" href="/films">Movies in the Dunes</a>
      </div>
      <div>
        <ul class="nav navbar-nav">
          <li><a href="/films">Home</a></li>
        </ul>
      </div>
    </div>
  </nav>
</header>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>